<a href="https://colab.research.google.com/github/Kx9357zl/Projects-for-Linear-Algebra/blob/main/Copy_of_Sports_Teams_Rankings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the preliminary code

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A   


def is_singular(matrix):
  singular = True
  notsingular = False

  (mr, mc) = matrix.shape
  
  return_value = notsingular
  if (mc - np.linalg.linalg.matrix_rank(matrix) > 0) :
    return_value = singular
  return return_value
 
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


# Ranking Teams based on games

From our packet, we saw there were five games:

Home  | Away
------|------
Winona State 16 | Sioux Falls 15
Winona State 34 | Augustana 20
Sioux Falls 51  | Augustana 13
Duluth 28       |  Augustana 17
Winona State 17 | Duluth 37

Let's encode this system into a matrix.

The unknown rankings are $r_w, r_s, r_a, r_d$.

The system looks like $M \vec{x} = \vec{b}$, or

$$
\left( \begin{array}{cccc} 1 & -1 & 0 & 0 \\ 1 & 0 & -1 & 0 \\ 0 & 1 & -1 & 0 \\ 0 & 0 & -1 & 1 \\ -1 & 0  & 0 & 1 \\ \end{array} \right) \, \left( \begin{array}{c} r_w \\ r_s \\ r_a \\ r_d \\ \end{array} \right) = \left( \begin{array}{c} 1 \\ 14 \\ 38 \\ 11 \\ 20 \\ \end{array} \right)$$

We'll solve this system using least squares 
$$M^T I M \vec{x} = M^T I \vec{b} $$

$$ \vec{x} = \left( M^T I M  \right)^{-1} M^T I \vec{b} $$






In [ ]:
# create the matrix:
M = np.matrix([[1, 0, 0, 0, -1, 0, 0],
              [1, -1, 0, 0, 0, 0, 0], 
              [1, 0, 0, 0, 0, 0, -1], 
             [-1, 0, 1, 0, 0, 0, 0],
             [1, 0, 0, 0, -1, 0, 0],
             [-1, 0, 1, 0, 0, 0, 0],
             [1, 0, 0, 0, 0, 0, -1],
             [-1, 0, 0, 1, 0, 0, 0],
             [-1, 0, 0, 0, 0, 1, 0],
             [-1, 0, 1, 0, 0, 0, 0],
             [0, -1, 0, 1, 0, 0, 0],
             [0, 1, -1, 0, 0, 0, 0],
             [0, -1, 1, 0, 0, 0, 0],
             [0, -1, 0, 0, 0, 1, 0],
             [0, 1, 0, 0, -1, 0, 0],
             [0, 1, 0, 0, 0, -1, 0],
             [0, -1, 0, 1, 0, 0, 0],
             [0, -1, 0, 0, 0, 0, 1],
             [0, -1, 0, 0, 1, 0, 0],
             [0, 0, 1, 0, -1, 0, 0],
             [0, 0, 1, 0, 0, 0, -1],
             [0, 0, 1, 0, 0, 0, -1],
             [0, 0, -1, 1, 0, 0, 0],
             [0, 0, 1, 0, -1, 0, 0],
             [0, 0, 0, 1, 0, -1, 0],
             [0, 0, 0, 1, 0, 0, -1],
             [0, 0, 0, 1, -1, 0, 0],
             [0, 0, 0, 1, 0, 0, -1],
             [0, 0, 0, 1, -1, 0, 0],
             [0, 0, 0, 0, -1, 1, 0],
             [0, 0, 0, 0, -1, 0, 1],
             [0, 0, 0, 0, 0, 1, -1]])


# create the vector for the right hand side:
pts = np.matrix([[14], [12], [16], [15], [13], [15], [17], [5], [4], [4], [27], [7], [15], [19], [18], [3], [31], [7], [4], [15], [15], [23], [5], [38], [12], [25], [5], [7], [16], [17], [1], [5]])
 
#Make sure the system looks appropriate:
print(np.c_[M,pts])

[[ 1  0  0  0 -1  0  0 14]
 [ 1 -1  0  0  0  0  0 12]
 [ 1  0  0  0  0  0 -1 16]
 [-1  0  1  0  0  0  0 15]
 [ 1  0  0  0 -1  0  0 13]
 [-1  0  1  0  0  0  0 15]
 [ 1  0  0  0  0  0 -1 17]
 [-1  0  0  1  0  0  0  5]
 [-1  0  0  0  0  1  0  4]
 [-1  0  1  0  0  0  0  4]
 [ 0 -1  0  1  0  0  0 27]
 [ 0  1 -1  0  0  0  0  7]
 [ 0 -1  1  0  0  0  0 15]
 [ 0 -1  0  0  0  1  0 19]
 [ 0  1  0  0 -1  0  0 18]
 [ 0  1  0  0  0 -1  0  3]
 [ 0 -1  0  1  0  0  0 31]
 [ 0 -1  0  0  0  0  1  7]
 [ 0 -1  0  0  1  0  0  4]
 [ 0  0  1  0 -1  0  0 15]
 [ 0  0  1  0  0  0 -1 15]
 [ 0  0  1  0  0  0 -1 23]
 [ 0  0 -1  1  0  0  0  5]
 [ 0  0  1  0 -1  0  0 38]
 [ 0  0  0  1  0 -1  0 12]
 [ 0  0  0  1  0  0 -1 25]
 [ 0  0  0  1 -1  0  0  5]
 [ 0  0  0  1  0  0 -1  7]
 [ 0  0  0  1 -1  0  0 16]
 [ 0  0  0  0 -1  1  0 17]
 [ 0  0  0  0 -1  0  1  1]
 [ 0  0  0  0  0  1 -1  5]]


In [ ]:
# Generate the transpose of M:
MT = M.transpose()

print("The Transpose of M is:")
print(MT)

# and find MT*M and MT*pts:
print("\n")
print("MT * M is: ")
MTM = MT * M
print(MTM)

print("\n")
print("MT * pts is:")
MTpts = MT * pts
print(MTpts)


The Transpose of M is:
[[ 1  1  1 -1  1 -1  1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0  0 -1  1 -1 -1  1  1 -1 -1 -1  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  1  0  0  0  1  0 -1  1  0  0  0  0  0  0  1  1  1 -1  1
   0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0  1  0  0  0  0  0  1  0
   1  1  1  1  1  0  0  0]
 [-1  0  0  0 -1  0  0  0  0  0  0  0  0  0 -1  0  0  0  1 -1  0  0  0 -1
   0  0 -1  0 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  1  0 -1  0  0  0  0  0  0  0  0
  -1  0  0  0  0  1  0  1]
 [ 0  0 -1  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0 -1 -1  0  0
   0 -1  0 -1  0  0  1 -1]]


MT * M is: 
[[10 -1 -3 -1 -2 -1 -2]
 [-1 10 -2 -2 -2 -2 -1]
 [-3 -2 10 -1 -2  0 -2]
 [-1 -2 -1  9 -2 -1 -2]
 [-2 -2 -2 -2 10 -1 -1]
 [-1 -2  0 -1 -1  6 -1]
 [-2 -1 -2 -2 -1 -1  9]]


MT * pts is:
[[  29]
 [ -87]
 [ 128]
 [ 133]
 [-133]
 [  30]
 [-100]]


If $M^T M$ has an inverse, then we can use it.  But, if $M^T M$ is singular, then it doesn't have an inverse.  In this situation, we need to replace every entry in one row (say the bottom row) of $M^T M$ and $M^T \vec{pts}$ with 1's.  (This knocks the system out of *not* having an inverse, so it will now have an inverse.)

In [ ]:
#  Check if MTM is singular
is_singular(MT*M)

True

In [ ]:
# If MTM is singular, then adjust one row of MTM and MT pts to be just 1's:

#MTM[7] is the entire 4th row of MTM, 
#so MTM[7] = 1 will put 1's in MTM's 4th row.

MTM[6] = 1
MTpts[6] = 1

print("MTM is now: ")
print(MTM)

print("and MTpts is now:")
print(MTpts)

print("Is our modified MTM singular?")
is_singular(MTM)

MTM is now: 
[[10 -1 -3 -1 -2 -1 -2]
 [-1 10 -2 -2 -2 -2 -1]
 [-3 -2 10 -1 -2  0 -2]
 [-1 -2 -1  9 -2 -1 -2]
 [-2 -2 -2 -2 10 -1 -1]
 [-1 -2  0 -1 -1  6 -1]
 [ 1  1  1  1  1  1  1]]
and MTpts is now:
[[  29]
 [ -87]
 [ 128]
 [ 133]
 [-133]
 [  30]
 [   1]]
Is our modified MTM singular?


False

In [ ]:
#Find our solution using the inverse of MTM:

#First, find the inverse of MTM:
MTMI = np.linalg.inv(MTM)

print("The inverse of MTM is:")
print(MTMI)

#Now, use the inverse of MTM to solve for the rankings:

print("\n")
print("The solution are rankings:")
MTMI * MTpts

The inverse of MTM is:
[[ 8.47282791e-02 -9.08800754e-03  8.21486476e-03 -9.35066672e-03
  -8.26182504e-04 -1.44136213e-02  1.42857143e-01]
 [ 5.69890821e-04  9.25260729e-02  6.92226323e-03  8.49503455e-03
   8.41146117e-03  9.94523158e-03  1.42857143e-01]
 [ 7.92991935e-03 -3.02058054e-03  8.65454030e-02 -8.88822738e-03
  -2.74598231e-04 -2.50218684e-02  1.42857143e-01]
 [-8.32788780e-03 -1.40084895e-04 -7.58050305e-03  9.23414155e-02
  -1.27349904e-05 -9.85608665e-03  1.42857143e-01]
 [ 7.71820013e-03  7.29794545e-03  8.55472982e-03  7.50886873e-03
   9.15725405e-02 -3.57694043e-03  1.42857143e-01]
 [-1.05143265e-03  1.36495219e-02 -1.13747343e-02  2.48332313e-03
   1.24086563e-03  1.47852443e-01  1.42857143e-01]
 [-9.15669689e-02 -1.01224867e-01 -9.12820235e-02 -9.25897479e-02
  -1.00111352e-01 -1.04929158e-01  1.42857143e-01]]


The solution are rankings:


matrix([[  2.87597154],
        [ -6.69486247],
        [  9.81715817],
        [ 10.93065081],
        [-10.46100745],
        [  2.06971134],
        [ -7.53762195]])

#  Game Data  - Fall Sports

Find the game data for the four teams in the NFC North and NFC South.

The teams are:

* **NFC North:**  Green Bay Packers, Chicago Bears, Detroit Lions, Minnesota Vikings
* **NFC South:**  Atlanta Falcons, Carolina Panthers, New Orleans Saints, Tampa Bay Buccaneers


It may be helpful to do a google search to find the data.

Be sure to create your matrix on the handout, then enter the data for the system below.

# Game Data - Spring Sports

Find the game data for the seven teams in the Western Division for Men's Big Ten Basketball.

**The teams:**  Wisconsin, Minnesota, Iowa, Illinois, Nebraska, Purdue, and Northewstern.

I've provided **most** of the data, but you have to do a Google search to find the scores for the last two teams.

Be sure to create your matrix on the handout, then enter the data for the system below.


In [ ]:
# create the matrix:
M = np.matrix([[1, 0, 0, 0, -1, 0, 0],
              [1, -1, 0, 0, 0, 0, 0], 
              [1, 0, 0, 0, 0, 0, -1], 
             [-1, 0, 1, 0, 0, 0, 0],
             [1, 0, 0, 0, -1, 0, 0],
             [-1, 0, 1, 0, 0, 0, 0],
             [1, 0, 0, 0, 0, 0, -1],
             [-1, 0, 0, 1, 0, 0, 0],
             [-1, 0, 0, 0, 0, 1, 0],
             [-1, 0, 1, 0, 0, 0, 0],
             [0, -1, 0, 1, 0, 0, 0],
             [0, 1, -1, 0, 0, 0, 0],
             [0, -1, 1, 0, 0, 0, 0],
             [0, -1, 0, 0, 0, 1, 0],
             [0, 1, 0, 0, -1, 0, 0],
             [0, 1, 0, 0, 0, -1, 0],
             [0, -1, 0, 1, 0, 0, 0],
             [0, -1, 0, 0, 0, 0, 1],
             [0, -1, 0, 0, 1, 0, 0],
             [0, 0, 1, 0, -1, 0, 0],
             [0, 0, 1, 0, 0, 0, -1],
             [0, 0, 1, 0, 0, 0, -1],
             [0, 0, -1, 1, 0, 0, 0],
             [0, 0, 1, 0, -1, 0, 0],
             [0, 0, 0, 1, 0, -1, 0],
             [0, 0, 0, 1, 0, 0, -1],
             [0, 0, 0, 1, -1, 0, 0],
             [0, 0, 0, 1, 0, 0, -1],
             [0, 0, 0, 1, -1, 0, 0],
             [0, 0, 0, 0, -1, 1, 0],
             [0, 0, 0, 0, -1, 0, 1],
             [0, 0, 0, 0, 0, 1, -1]])


# create the vector for the right hand side:
pts = np.matrix([[14], [12], [16], [15], [13], [15], [17], [5], [4], [4], [27], [7], [15], [19], [18], [3], [31], [7], [4], [15], [15], [23], [5], [38], [12], [25], [5], [7], [16], [17], [1], [5]])
 
#Make sure the system looks appropriate:
print(np.c_[M,pts])

[[ 1  0  0  0 -1  0  0 14]
 [ 1 -1  0  0  0  0  0 12]
 [ 1  0  0  0  0  0 -1 16]
 [-1  0  1  0  0  0  0 15]
 [ 1  0  0  0 -1  0  0 13]
 [-1  0  1  0  0  0  0 15]
 [ 1  0  0  0  0  0 -1 17]
 [-1  0  0  1  0  0  0  5]
 [-1  0  0  0  0  1  0  4]
 [-1  0  1  0  0  0  0  4]
 [ 0 -1  0  1  0  0  0 27]
 [ 0  1 -1  0  0  0  0  7]
 [ 0 -1  1  0  0  0  0 15]
 [ 0 -1  0  0  0  1  0 19]
 [ 0  1  0  0 -1  0  0 18]
 [ 0  1  0  0  0 -1  0  3]
 [ 0 -1  0  1  0  0  0 31]
 [ 0 -1  0  0  0  0  1  7]
 [ 0 -1  0  0  1  0  0  4]
 [ 0  0  1  0 -1  0  0 15]
 [ 0  0  1  0  0  0 -1 15]
 [ 0  0  1  0  0  0 -1 23]
 [ 0  0 -1  1  0  0  0  5]
 [ 0  0  1  0 -1  0  0 38]
 [ 0  0  0  1  0 -1  0 12]
 [ 0  0  0  1  0  0 -1 25]
 [ 0  0  0  1 -1  0  0  5]
 [ 0  0  0  1  0  0 -1  7]
 [ 0  0  0  1 -1  0  0 16]
 [ 0  0  0  0 -1  1  0 17]
 [ 0  0  0  0 -1  0  1  1]
 [ 0  0  0  0  0  1 -1  5]]


In [ ]:
# Generate the transpose of M:
MT = M.transpose()

print("The Transpose of M is:")
print(MT)

# and find MT*M and MT*pts:
print("\n")
print("MT * M is: ")
MTM = MT * M
print(MTM)

print("\n")
print("MT * pts is:")
MTpts = MT * pts
print(MTpts)


The Transpose of M is:
[[ 1  1  1 -1  1 -1  1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0  0 -1  1 -1 -1  1  1 -1 -1 -1  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  1  0  0  0  1  0 -1  1  0  0  0  0  0  0  1  1  1 -1  1
   0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0  1  0  0  0  0  0  1  0
   1  1  1  1  1  0  0  0]
 [-1  0  0  0 -1  0  0  0  0  0  0  0  0  0 -1  0  0  0  1 -1  0  0  0 -1
   0  0 -1  0 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  1  0 -1  0  0  0  0  0  0  0  0
  -1  0  0  0  0  1  0  1]
 [ 0  0 -1  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0  0 -1 -1  0  0
   0 -1  0 -1  0  0  1 -1]]


MT * M is: 
[[10 -1 -3 -1 -2 -1 -2]
 [-1 10 -2 -2 -2 -2 -1]
 [-3 -2 10 -1 -2  0 -2]
 [-1 -2 -1  9 -2 -1 -2]
 [-2 -2 -2 -2 10 -1 -1]
 [-1 -2  0 -1 -1  6 -1]
 [-2 -1 -2 -2 -1 -1  9]]


MT * pts is:
[[  29]
 [ -87]
 [ 128]
 [ 133]
 [-133]
 [  30]
 [-100]]


In [ ]:
#  Check if MTM is singular
is_singular(MT*M)

True

In [ ]:
# Careful - you might not need to do this!  
# Be sure to check whether MTM is singular on the previous line.

# If MTM is singular, then adjust one row of MTM and MT pts to be just 1's:

#MTM[3] is the entire 4th row of MTM, 
#so MTM[3] = 1 will put 1's in MTM's 4th row.

MTM[6] = 1
MTpts[6] = 1

print("MTM is now: ")
print(MTM)

print("and MTpts is now:")
print(MTpts)

print("Is our modified MTM singular?")
is_singular(MTM)

MTM is now: 
[[10 -1 -3 -1 -2 -1 -2]
 [-1 10 -2 -2 -2 -2 -1]
 [-3 -2 10 -1 -2  0 -2]
 [-1 -2 -1  9 -2 -1 -2]
 [-2 -2 -2 -2 10 -1 -1]
 [-1 -2  0 -1 -1  6 -1]
 [ 1  1  1  1  1  1  1]]
and MTpts is now:
[[  29]
 [ -87]
 [ 128]
 [ 133]
 [-133]
 [  30]
 [   1]]
Is our modified MTM singular?


False

In [ ]:
#Find our solution using the inverse of MTM:

#First, find the inverse of MTM:
MTMI = np.linalg.inv(MTM)

print("The inverse of MTM is:")
print(MTMI)

#Now, use the inverse of MTM to solve for the rankings:

print("\n")
print("The solution are rankings:")
MTMI * MTpts

The inverse of MTM is:
[[ 8.47282791e-02 -9.08800754e-03  8.21486476e-03 -9.35066672e-03
  -8.26182504e-04 -1.44136213e-02  1.42857143e-01]
 [ 5.69890821e-04  9.25260729e-02  6.92226323e-03  8.49503455e-03
   8.41146117e-03  9.94523158e-03  1.42857143e-01]
 [ 7.92991935e-03 -3.02058054e-03  8.65454030e-02 -8.88822738e-03
  -2.74598231e-04 -2.50218684e-02  1.42857143e-01]
 [-8.32788780e-03 -1.40084895e-04 -7.58050305e-03  9.23414155e-02
  -1.27349904e-05 -9.85608665e-03  1.42857143e-01]
 [ 7.71820013e-03  7.29794545e-03  8.55472982e-03  7.50886873e-03
   9.15725405e-02 -3.57694043e-03  1.42857143e-01]
 [-1.05143265e-03  1.36495219e-02 -1.13747343e-02  2.48332313e-03
   1.24086563e-03  1.47852443e-01  1.42857143e-01]
 [-9.15669689e-02 -1.01224867e-01 -9.12820235e-02 -9.25897479e-02
  -1.00111352e-01 -1.04929158e-01  1.42857143e-01]]


The solution are rankings:


matrix([[  2.87597154],
        [ -6.69486247],
        [  9.81715817],
        [ 10.93065081],
        [-10.46100745],
        [  2.06971134],
        [ -7.53762195]])